GET http://localhost:1337/api/movies
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk4NDExOTQ3LCJleHAiOjE3MDEwMDM5NDd9.5uL2QbPaOmHinXThaDYPjdmFBL0HByOzIXiW4jpjikw

###
GET http://localhost:1337/api/actors
###


POST http://localhost:1337/api/actors
Content-Type: application/json

{
    "data": {
        "Name": "Jeremy",
        "LastName": "FRAZIER"
    }   
}

###
POST http://localhost:1337/api/movies
Content-Type: application/json

{
    "data":{
        "title": "hostel",
        "description": "tata",
        "releaseDate": "2001-01-01",
        "director": "Jeremy"
    }
}

###

GET http://localhost:1337/api/movies?filters[title][$startsWith]=h

###

PUT http://localhost:1337/api/actors/2
Content-Type: application/json

{
    "data":{
        "LastName": "BRAZIER"
    }
}

###

POST http://localhost:1337/api/auth/local
Accept: application/json
Content-Type: application/json

{
  "identifier": "thomaslaforge@gmail.com",
  "password": "admin1234"
}

###

GET http://localhost:1337/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk4NDExOTQ3LCJleHAiOjE3MDEwMDM5NDd9.5uL2QbPaOmHinXThaDYPjdmFBL0HByOzIXiW4jpjikw

###
POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
  "identifier": "thomaslaforge@gmail.com",
  "password": "admin1234"
}

###

POST http://localhost:1337/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0b210b20iLCJlbWFpbCI6InRob21hc2xhZm9yZ2VAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wN1QwOTowODo1Mi43NzdaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wN1QwOToxMToxNC42MDdaIiwiaWF0IjoxNzAxOTQwMzIxfQ.tuzC-PVTqhF4qFaYOhC4wPxvK48EvNqtV-dh0moZLvI

{
  "currentPassword": "admin1234",
  "password": "tomtom1234",
  "passwordConfirmation": "tomtom1234"
}
